# All Imports & Loading Data

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

train = pd.read_csv(r"../Data/train.csv")

print(train.columns.tolist())
print(train.shape)
display(train.head())
print(train.info())

['Id', 'AB', 'AF', 'AH', 'AM', 'AR', 'AX', 'AY', 'AZ', 'BC', 'BD ', 'BN', 'BP', 'BQ', 'BR', 'BZ', 'CB', 'CC', 'CD ', 'CF', 'CH', 'CL', 'CR', 'CS', 'CU', 'CW ', 'DA', 'DE', 'DF', 'DH', 'DI', 'DL', 'DN', 'DU', 'DV', 'DY', 'EB', 'EE', 'EG', 'EH', 'EJ', 'EL', 'EP', 'EU', 'FC', 'FD ', 'FE', 'FI', 'FL', 'FR', 'FS', 'GB', 'GE', 'GF', 'GH', 'GI', 'GL', 'Class']
(617, 58)

,Id,AB,AF,AH,AM,AR,AX,AY,AZ,BC,...,FL,FR,FS,GB,GE,GF,GH,GI,GL,Class
0,000ff2bfdfe9,0.209377,3109.03329,85.200147,22.394407,8.138688,0.699861,0.025578,9.812214,5.555634,...,7.298162,1.73855,0.094822,11.339138,72.611063,2003.810319,22.136229,69.834944,0.120343,1
1,007255e47698,0.145282,978.76416,85.200147,36.968889,8.138688,3.632190,0.025578,13.517790,1.229900,...,0.173229,0.49706,0.568932,9.292698,72.611063,27981.562750,29.135430,32.131996,21.978000,0
2,013f2bd269f5,0.470030,2635.10654,85.200147,32.360553,8.138688,6.732840,0.025578,12.824570,1.229900,...,7.709560,0.97556,1.198821,37.077772,88.609437,13676.957810,28.022851,35.192676,0.196941,0
3,043ac50845d5,0.252107,3819.65177,120.201618,77.112203,8.138688,3.685344,0.025578,11.053708,1.229900,...,6.122162,0.49706,0.284466,18.529584,82.416803,2094.262452,39.948656,90.493248,0.155829,0
4,044fb8a146ec,0.380297,3733.04844,85.200147,14.103738,8.138688,3.942255,0.054810,3.396778,102.151980,...,8.153058,48.50134,0.121914,16.408728,146.109943,8524.370502,45.381316,36.262628,0.096614,1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 617 entries, 0 to 616
Data columns (total 58 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Id      617 non-null    object
 1   AB      617 non-null    float64
 2   AF      617 non-null    float64
 3   AH      617 non-null    float64
 4   AM      617 non-null    float64
 5   AR      617 non-null    float64
 6   AX      617 non-null    float64
 7   AY      617 non-null    float64
 8   AZ      617 non-null    float64
 9   BC      617 non-null    float64
 10  BD      617 non-null    float64
 11  BN      617 non-null    float64
 12  BP      617 non-null    float64
 13  BQ      557 non-null    float64
 14  BR      617 non-null    float64
 15  BZ      617 non-null    float64
 16  CB      615 non-null    float64
 17  CC      614 non-null    float64
 18  CD      617 non-null    float64
 19  CF      617 non-null    float64
 20  CH      617 non-null    float64
 21  CL      617 non-null    float64
 22  CR      617 non-null    float64
 23  CS      617 non-null    float64
 24  CU      617 non-null    float64
 25  CW      617 non-null    float64
 26  DA      617 non-null    float64
 27  DE      617 non-null    float64
 28  DF      617 non-null    float64
 29  DH      617 non-null    float64
 30  DI      617 non-null    float64
 31  DL      617 non-null    float64
 32  DN      617 non-null    float64
 33  DU      616 non-null    float64
 34  DV      617 non-null    float64
 35  DY      617 non-null    float64
 36  EB      617 non-null    float64
 37  EE      617 non-null    float64
 38  EG      617 non-null    float64
 39  EH      617 non-null    float64
 40  EJ      617 non-null    object
 41  EL      557 non-null    float64
 42  EP      617 non-null    float64
 43  EU      617 non-null    float64
 44  FC      616 non-null    float64
 45  FD      617 non-null    float64
 46  FE      617 non-null    float64
 47  FI      617 non-null    float64
 48  FL      616 non-null    float64
 49  FR      617 non-null    float64
 50  FS      615 non-null    float64
 51  GB      617 non-null    float64
 52  GE      617 non-null    float64
 53  GF      617 non-null    float64
 54  GH      617 non-null    float64
 55  GI      617 non-null    float64
 56  GL      616 non-null    float64
 57  Class   617 non-null    int64
dtypes: float64(55), int64(1), object(2)
memory usage: 279.7+ KB
None

In [2]:
test = pd.read_csv(r"../Data/test.csv")

print(test.columns.tolist())
print(test.shape)
display(test.head())
print(test.info())

['Id', 'AB', 'AF', 'AH', 'AM', 'AR', 'AX', 'AY', 'AZ', 'BC', 'BD ', 'BN', 'BP', 'BQ', 'BR', 'BZ', 'CB', 'CC', 'CD ', 'CF', 'CH', 'CL', 'CR', 'CS', 'CU', 'CW ', 'DA', 'DE', 'DF', 'DH', 'DI', 'DL', 'DN', 'DU', 'DV', 'DY', 'EB', 'EE', 'EG', 'EH', 'EJ', 'EL', 'EP', 'EU', 'FC', 'FD ', 'FE', 'FI', 'FL', 'FR', 'FS', 'GB', 'GE', 'GF', 'GH', 'GI', 'GL']
(5, 57)

,Id,AB,AF,AH,AM,AR,AX,AY,AZ,BC,...,FI,FL,FR,FS,GB,GE,GF,GH,GI,GL
0,00eed32682bb,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,010ebe33f668,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,02fa521e1838,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,040e15f562a2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,046e85c7cc7f,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 57 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Id      5 non-null      object
 1   AB      5 non-null      float64
 2   AF      5 non-null      float64
 3   AH      5 non-null      float64
 4   AM      5 non-null      float64
 5   AR      5 non-null      float64
 6   AX      5 non-null      float64
 7   AY      5 non-null      float64
 8   AZ      5 non-null      float64
 9   BC      5 non-null      float64
 10  BD      5 non-null      float64
 11  BN      5 non-null      float64
 12  BP      5 non-null      float64
 13  BQ      5 non-null      float64
 14  BR      5 non-null      float64
 15  BZ      5 non-null      float64
 16  CB      5 non-null      float64
 17  CC      5 non-null      float64
 18  CD      5 non-null      float64
 19  CF      5 non-null      float64
 20  CH      5 non-null      float64
 21  CL      5 non-null      float64
 22  CR      5 non-null      float64
 23  CS      5 non-null      float64
 24  CU      5 non-null      float64
 25  CW      5 non-null      float64
 26  DA      5 non-null      float64
 27  DE      5 non-null      float64
 28  DF      5 non-null      float64
 29  DH      5 non-null      float64
 30  DI      5 non-null      float64
 31  DL      5 non-null      float64
 32  DN      5 non-null      float64
 33  DU      5 non-null      float64
 34  DV      5 non-null      float64
 35  DY      5 non-null      float64
 36  EB      5 non-null      float64
 37  EE      5 non-null      float64
 38  EG      5 non-null      float64
 39  EH      5 non-null      float64
 40  EJ      5 non-null      object
 41  EL      5 non-null      float64
 42  EP      5 non-null      float64
 43  EU      5 non-null      float64
 44  FC      5 non-null      float64
 45  FD      5 non-null      float64
 46  FE      5 non-null      float64
 47  FI      5 non-null      float64
 48  FL      5 non-null      float64
 49  FR      5 non-null      float64
 50  FS      5 non-null      float64
 51  GB      5 non-null      float64
 52  GE      5 non-null      float64
 53  GF      5 non-null      float64
 54  GH      5 non-null      float64
 55  GI      5 non-null      float64
 56  GL      5 non-null      float64
dtypes: float64(55), object(2)
memory usage: 2.4+ KB
None

# Cleaning Data

### Column Check
Checking whether the train and test dataset have the same feature columns, also compare the column difference between them.

In [3]:
train_cols = set(train.columns)
test_cols = set(test.columns)

train_only = train_cols - test_cols
test_only = test_cols - train_cols

id_col = "Id"
label_col = "Class"

print("Columns only in train:", train_only if train_only else None)
print("Columns only in test:", test_only if test_only else None)
print("Id in train:", id_col in train.columns, "| Id in test:", id_col in test.columns)
print("Label (Class) in train:", label_col in train.columns)

Columns only in train: {'Class'}
Columns only in test: None
Id in train: True | Id in test: True
Label (Class) in train: True

### Optional: Load greeks.csv

The competition also provides an additional file called `greeks.csv`.

Supplemental metadata, only available for the training set:
- ```Alpha``` Identifies the type of age-related condition, if present.
    - ```A``` No age-related condition. Corresponds to class 0.
    - ```B, D, G``` The three age-related conditions. Correspond to class 1.
- ```Beta, Gamma, Delta``` Three experimental characteristics.
- ```Epsilon``` The date the data for this subject was collected. Note that all of the data in the test set was collected after the training set was collected.

(This step is optional and safe to skip if not needed.)

In [4]:
greeks = pd.read_csv(r"../Data/greeks.csv")
print(greeks.columns.tolist())
print(greeks.shape)
display(greeks.head())

['Id', 'Alpha', 'Beta', 'Gamma', 'Delta', 'Epsilon']
(617, 6)

             Id Alpha Beta Gamma Delta    Epsilon
0  000ff2bfdfe9     B    C     G     D  3/19/2019
1  007255e47698     A    C     M     B    Unknown
2  013f2bd269f5     A    C     M     B    Unknown
3  043ac50845d5     A    C     M     B    Unknown
4  044fb8a146ec     D    B     F     B  3/25/2020

In [5]:
print("train before merge: ", train.shape)
train = train.merge(greeks, on="Id", how="left")
print("train after merge: ", train.shape)

train before merge:  (617, 58)
train after merge:  (617, 63)

### Check for Duplicates and Missing Values

1. Removes exact duplicate rows (if any exist)  
2. Computes the percentage of missing values per column  
3. Displays the top columns with missing data  

Since the dataset is small, we only remove exact duplicates and do not drop rows due to missing values.

In [11]:
# remove exact duplicates
before = train.shape[0]
train = train.drop_duplicates()
after = train.shape[0]
print("Dropped duplicates:", before - after)

# missingness summary
missing_perc = train.isna().mean().sort_values(ascending=False)
missing_perc = missing_frac[missing_frac > 0]

print("Columns with missing values:", len(missing_perc))
display((missing_perc * 100).round(4).head(20).to_frame("missing %"))

Dropped duplicates: 0
Columns with missing values: 9

    missing %
BQ     9.7245
EL     9.7245
CC     0.4862
FS     0.3241
CB     0.3241
DU     0.1621
FC     0.1621
GL     0.1621
FL     0.1621

### Fill Missing Values and Align Train/Test Columns

Missing values are handled using statistics computed from the training set:

- Numeric columns → filled with median  
- Categorical columns → filled with mode  

After filling, we align train and test to ensure they have identical feature columns before modeling.

In [13]:
# create a list of all columns except the label
feature_cols = [col for col in train.columns if col != label_col]

# loop through each feature column and fill missing values
for col in feature_cols:
    
    # exclude label_col if not done so
    if col == label_col:
        continue

    # if the column is numeric, fill missing values with the median
    if train[col].dtype != "object":
        median = train[col].median()
        train[col] = train[col].fillna(median)

        # use the same median from train to fill missing values in test
        if col in test.columns:
            test[col] = test[col].fillna(median)

    # if the column is categorical/object, fill missing values with the mode
    else:
        mode = train[col].mode()
        mode = mode[0] if len(mode) > 0 else None
        train[col] = train[col].fillna(mode)

        # use the same mode from train to fill missing values in test
        if col in test.columns:
            test[col] = test[col].fillna(mode)

# remove the label temporarily so train can be aligned with test
train_no_label = train.drop(columns=[label_col])

# align train and test to make sure they have the same feature columns
# join="left" keeps the train feature structure
# fill_value=0 fills any missing columns created during alignment
train_no_label, test = train_no_label.align(test, join="left", axis=1, fill_value=0)

# add the label column back to train
train = pd.concat([train_no_label, train[[label_col]]], axis=1)

print("Aligned shapes -> train:", train.shape, "test:", test.shape)

Aligned shapes -> train: (617, 63) test: (5, 62)

In [14]:
# check missing values after cleaning
train_missing_after = train.isna().sum().sum()
test_missing_after = test.isna().sum().sum()

print("Total missing values in cleaned train:", train_missing_after)
print("Total missing values in cleaned test:", test_missing_after)

Total missing values in cleaned train: 0
Total missing values in cleaned test: 0

### Save Cleaned Train and Test Files

After preprocessing, we save cleaned versions of both datasets.

- train.csv -> clean_train.csv
- test.csv -> clean_test.csv

In [16]:
out_dir = Path("../Data")
out_dir.mkdir(parents=True, exist_ok=True)

train.to_csv(out_dir / "clean_train.csv", index=False)
test.to_csv(out_dir / "clean_test.csv", index=False)

print("Saved:")
print(out_dir / "clean_train.csv")
print(out_dir / "clean_test.csv")

Saved:
..\Data\clean_train.csv
..\Data\clean_test.csv

In [18]:
# loading cleaned data
clean_train = pd.read_csv(r"Data/clean_train.csv")
clean_test = pd.read_csv(r"Data/clean_test.csv")

print("loading cleaned data...")

print(clean_train.shape)
print(clean_test.shape)

display(clean_train.head())
display(clean_test.head())

loading cleaned data...
(617, 63)
(5, 62)

,Id,AB,AF,AH,AM,AR,AX,AY,AZ,BC,...,GF,GH,GI,GL,Alpha,Beta,Gamma,Delta,Epsilon,Class
0,000ff2bfdfe9,0.209377,3109.03329,85.200147,22.394407,8.138688,0.699861,0.025578,9.812214,5.555634,...,2003.810319,22.136229,69.834944,0.120343,B,C,G,D,3/19/2019,1
1,007255e47698,0.145282,978.76416,85.200147,36.968889,8.138688,3.632190,0.025578,13.517790,1.229900,...,27981.562750,29.135430,32.131996,21.978000,A,C,M,B,Unknown,0
2,013f2bd269f5,0.470030,2635.10654,85.200147,32.360553,8.138688,6.732840,0.025578,12.824570,1.229900,...,13676.957810,28.022851,35.192676,0.196941,A,C,M,B,Unknown,0
3,043ac50845d5,0.252107,3819.65177,120.201618,77.112203,8.138688,3.685344,0.025578,11.053708,1.229900,...,2094.262452,39.948656,90.493248,0.155829,A,C,M,B,Unknown,0
4,044fb8a146ec,0.380297,3733.04844,85.200147,14.103738,8.138688,3.942255,0.054810,3.396778,102.151980,...,8524.370502,45.381316,36.262628,0.096614,D,B,F,B,3/25/2020,1

,Id,AB,AF,AH,AM,AR,AX,AY,AZ,BC,...,GE,GF,GH,GI,GL,Alpha,Beta,Gamma,Delta,Epsilon
0,00eed32682bb,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0
1,010ebe33f668,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0
2,02fa521e1838,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0
3,040e15f562a2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0
4,046e85c7cc7f,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0